//pkg install.js --targets node18-win-x64 --output install.exe


const { execSync } = require('child_process');
const path = require('path');
const fs = require('fs');
const os = require('os');

// ================= CONFIGURATION =================
const BACKEND_REPO = 'https://github.com/partglm/site.git';
const FRONTEND_REPO = 'https://github.com/partglm/site.git';
const BACKEND_DIR = path.join(process.cwd(), 'backend');   // ⚡ process.cwd() au lieu de __dirname
const FRONTEND_DIR = path.join(process.cwd(), 'frontend');
const BACKEND_BRANCH = 'backend';
const FRONTEND_BRANCH = 'frontend';

// Dossier global pour les scripts → placé dans %APPDATA%
const GLOBAL_SCRIPT_DIR = path.join(process.env.APPDATA, 'site-tools');
if (!fs.existsSync(GLOBAL_SCRIPT_DIR)) fs.mkdirSync(GLOBAL_SCRIPT_DIR, { recursive: true });

// Chemin du script batch
const BATCH_FILE = path.join(GLOBAL_SCRIPT_DIR, 'site.bat');

// ================= HELPERS =================
function cloneOrPull(repo, dir, branch) {
    if (fs.existsSync(dir)) {
        console.log(`Updating ${dir}...`);
        execSync('git pull', { cwd: dir, stdio: 'inherit' });
    } else {
        console.log(`Cloning ${repo} (${branch}) into ${dir}...`);
        execSync(`git clone --branch ${branch} ${repo} ${dir}`, { stdio: 'inherit' });
        execSync('npm install', { cwd: dir, stdio: 'inherit' });
    }
}

function createBatchFile() {
    const content = `
@echo off
REM Auto-generated by installer

SET BACKEND_DIR=${BACKEND_DIR}
SET FRONTEND_DIR=${FRONTEND_DIR}

IF "%1"=="debug" (
    start cmd /k "cd /d %BACKEND_DIR% && npm run debug"
    start cmd /k "cd /d %FRONTEND_DIR% && npm run debug"
) ELSE (
    start cmd /k "cd /d %BACKEND_DIR% && npm start"
    start cmd /k "cd /d %FRONTEND_DIR% && npm start"
)
`;
    fs.writeFileSync(BATCH_FILE, content, 'utf8');
    console.log(`✅ Batch file created at ${BATCH_FILE}`);
}

function addToWindowsPath(dir) {
    console.log(`Adding ${dir} to PATH (requires admin)...`);

    try {
        execSync(`setx PATH "%PATH%;${dir}"`, { stdio: 'inherit' });
        console.log('✅ PATH updated. Open a new terminal and type "site"!');
    } catch (err) {
        console.error('❌ Failed to update PATH automatically. Please add manually:', dir);
    }
}

// ================= MAIN =================
console.log('--- Installing Backend ---');
cloneOrPull(BACKEND_REPO, BACKEND_DIR, BACKEND_BRANCH);

console.log('--- Installing Frontend ---');
cloneOrPull(FRONTEND_REPO, FRONTEND_DIR, FRONTEND_BRANCH);

console.log('--- Creating start script ---');
createBatchFile();

console.log('--- Adding script folder to PATH ---');
addToWindowsPath(GLOBAL_SCRIPT_DIR);

console.log('--- Installation Complete ---');
console.log(`👉 You can now run "site" or "site debug" from any terminal!`);
